version: '3.8'
services:
  # app:
  #   container_name: app-dev
  #   image: app-dev
  #   build:
  #     context: ./gitpod-react
  #     target: development
  #   volumes:
  #     - ./gitpod-react/src:/app/src
  #   ports:
  #     - 3000:3000

  backend:
    container_name: gitpod-demo
    # image: gitpod-demo
    build:
      context: ./demo
      dockerfile: Dockerfile
      # target: development
    restart: always
    ports:
      - 8080:8080
    # volumes:
    #   - springboot-demo:/home/app
        

# volumes:
#   springboot-demo:
#     external: false
